baseURL = "https://tasekida.github.io/hands-on/"
canonifyurls = true
publishDir = "docs"

languageCode = "ja"
defaultContentLanguage = "ja"

title = "Hands on"
theme = "hugo-book"

timeZone = "Asia/Tokyo"
